[project]
name = "llm-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "isort>=5.13.2",
    "nbstripout>=0.8.1",
    "openai>=1.59.9",
    "python-dotenv>=1.0.1",
    "ruff>=0.9.2",
]
